apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sf-redis-slave
spec:
  serviceName: "svc-redis-slave"
  replicas: 3
  template:
    metadata:
      labels:
        name: sf-redis-slave
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cont-redis-slave
        image: h3crd-wlan1.chinacloudapp.cn:5000/redis:b14
        env:
        - name: SLAVE
          value: "true"
        - name: MASTER_HOST
          value: sf-redis-master-0.svc-redis-master
        - name: MASTER_PORT
          value: "6379"
        - name: SENTINEL_HOST
          value: sf-redis-sentinel-0.svc-redis-sentinel 
        - name: SENTINEL_PORT
          value: "26379"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redisslave
          mountPath: /data/redis/slave
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: redisslave
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
