apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sf-redis-master
spec:
  serviceName: "svc-redis-master"
  podManagementPolicy: "Parallel"
  replicas: 1
  template:
    metadata:
      labels:
        name: sf-redis-master
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cont-redis-master
        image: h3crd-wlan1.chinacloudapp.cn:5000/redis:beta
        imagePullPolicy: Always
        env:
        - name: MASTER
          value: "true"
        - name: SENTINEL_HOST
          value: sf-redis-sentinel-0.svc-redis-sentinel
        - name: SENTINEL_PORT
          value: "26379"
        - name: MASTER_PORT
          value: "6379"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redismaster
          mountPath: /data/redis
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: redismaster
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
