apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sf-redis-cluster
spec:
  serviceName: "svc-redis-cluster"
  replicas: 6
  template:
    metadata:
      labels:
        name: sf-redis-cluster
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cont-redis-cluster
        image: h3crd-wlan1.chinacloudapp.cn:5000/redis:beta
        env:
        - name: CLUSTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: rediscluster
          mountPath: /data/redis
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: rediscluster
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi