apiVersion: v1
kind: Service
metadata:
  name: svc-redis-sentinel
  labels:
    name: svc-redis-sentinel
spec:
  ports:
  - port: 6381
    targetPort: 6381
  clusterIP: None
  selector:
    name: sf-redis-sentinel
